### ISSUE TITLE
Chapter 13 (file 40) is much longer than the others.

### ISSUE THREAD

**Issue by timparenti** [laboon/ebook#11]
Chapter 13 ("Unit Testing") is far longer than any of the others.  The number of subsections involved causes slight formatting issues in the Table of Contents.

Consider splitting `text/40_unit_testing.md` into two or more chapters.

**Comment by laboon** [comment]
Fixed in commit 497cbedd400395c182be37f6c0992732df483f9f

**Comment by timparenti** [comment]
The newly-minted Chapter 14 ("Advanced Unit Testing", file 41) still has 10 sections, which means the aforementioned (minor) formatting issue remains.

Perhaps 14.7 ("Using Reflection to Test Private Methods in Java") could go under 14.6 ("Testing Private Methods")?

**Comment by laboon** [comment]
Fixed in commit 798bb3ba65427c7bbd83f05792a719223a610ed2
